import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/page/navbar/Navbar";
import Footer from "@/components/page/footer/Footer";
import "./globals.css";
import { getCurrentUser } from "@/actions/getCurrentUser";

// const inter = Inter({ subsets: ["latin"] });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const currentUser = await getCurrentUser();

type userType = {
  id: string;
  email: string;
  username: string;
  hashedPassword: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const getCurrentUsername = async () => {
  //   const currentUser = await getCurrentUser();

  //   return currentUser ? currentUser.username : "";
  // };

  // const currentUsername = await getCurrentUsername();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-col",
          fontSans.variable
        )}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
